apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw8-ingress
  namespace: mantogin-hw8
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "hw8-nginx"
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /billing
            pathType: Prefix
            backend:
              service:
                name: billing-load-balancer
                port:
                  number: 8001
          - path: /delivery
            pathType: Prefix
            backend:
              service:
                name: delivery-load-balancer
                port:
                  number: 8002
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: order-load-balancer
                port:
                  number: 8003
          - path: /warehouse
            pathType: Prefix
            backend:
              service:
                name: warehouse-load-balancer
                port:
                  number: 8004

